import type { NextPage } from 'next'
import Head from 'next/head'
import LogoBanner from '../../components/LogoBanner'

const Research: NextPage = () => {
  return (
    <>
      <Head>
        <title>Equity Research Competition - INFEST 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <LogoBanner />
      </div>
    </>
  )
}

export default Research
