import type { NextPage } from 'next'
import Head from 'next/head'
import LogoBanner from '../components/LogoBanner'
import About from '../components/About'
import Theme from '../components/Theme'
import Teaser from '../components/Teaser'
import CardDeck from '../components/CardDeck'
import Timeline from '../components/Timeline'
import FAQDeck from '../components/FAQDeck'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Beranda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <LogoBanner/>
        <About/>
        <Theme/>
        <Teaser/>
        <CardDeck />
        <Timeline />
        <FAQDeck />
      </div>
    </>
  )
}

export default Home
